# Basic Worker configuration
name = "cloudflare-worker-error-page"
main = "worker.js"
compatibility_date = "2025-08-24"


# KV namespace to store maintenance state
kv_namespaces = [
  { binding = "MAINTENANCE_KV", id = "d91ec4f6b9ab46dda308e7d2b45fc87a" }
]

[vars]

# Language setting (FR or EN)
LANGUAGE = "FR"

# FOR HAVE A RETURN TO THE LINE USE <br> IN MESSAGE

# For 503 errors when maintenance is activated
TEXT_MAINTENANCE_TYPE = "Maintenance serveur"
TEXT_MAINTENANCE_MESSAGE = "Je fais de nouvelles exp√©riences !! <br> Promis je me d√©p√™che ! üòó"
TEXT_MAINTENANCE_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/maintenance.gif"

# For 504 errors when internet connection is down
TEXT_BOX_ERROR_TYPE = "Erreur de connexion"
TEXT_BOX_ERROR_MESSAGE = "On dirait que ma box fibre a d√©cid√© de faire une pause, il va falloir patienter... üò© N‚Äôh√©sitez pas √† me le signaler quand m√™me !"
TEXT_BOX_ERROR_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/box_error.gif"

# For 500 errors when server probably crashed
TEXT_GENERIC_ERROR_TYPE = "Erreur serveur"
TEXT_GENERIC_ERRORR_MESSAGE = "Le serveur a s√ªrement d√ª crash... <br> N'h√©sitez pas √† me le signaler !"
TEXT_GENERIC_ERROR_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/generic_error.gif"

# For 503 errors when specific service is down
TEXT_CONTAINER_ERROR_TYPE = "Service indisponible"
TEXT_CONTAINER_ERROR_MESSAGE = "Service non d√©marr√© ou plant√© ! <br> N‚Äôh√©sitez pas √† me le signaler au cas o√π !"
TEXT_CONTAINER_ERROR_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/container_error.gif"

# Enable or disable 4G banner functionality
ENABLE_4G_BANNER = false
# Message for 4G banner when fiber is down
TEXT_4G_BANNER_MESSAGE = "Attention des lenteurs peuvent survenir, ma fibre est H.S. Le serveur fonctionne en 4G !"
