# Basic Worker configuration
name = "cloudflare-worker-error-page"
main = "worker.js"
compatibility_date = "2025-08-24"


# KV namespace to store maintenance state
kv_namespaces = [
  { binding = "MAINTENANCE_KV", id = "57a8af4a40c64e889cfacb226bf1ece4" }
]

# Enable logs in cloudflare for debug
[observability]
enabled = true

[vars]

# Language setting (FR or EN)
LANGUAGE = "FR"

# Enable/disable cache (true/false) for limite api call between this worker and the kv storage, in Cloudflare free plan You have only 100 000 reads per day 
ENABLE_CACHE = true
# Cache duration in ms (default: 60000 = 1 minute)
CACHE_TTL_MS = 60000

# Enable or disable the error reporting functionality
ENABLE_REPORT_ERROR = true
# Discord webhook URL for error reports
REPORT_ERROR_DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1411329377538674870/Y4ikyN_RCGFCu5DfRbGuxhIdA8mqLFckpu_zmHY5t6ewEehd9VRHxuz-VeGTE6t6bssC"
REPORT_ERROR_DISWCORD_CARD_TITLE = "üÜò Nouvelle erreur signal√©e"
REPORT_ERROR_DISWCORD_CARD_CODE_FIELD_NAME = "Code d'Erreur"
REPORT_ERROR_DISWCORD_CARD_SITE_FIELD_NAME = "Domaine"
REPORT_ERROR_BUTTON_TEXT = "Signaler cette erreur"
REPORT_ERROR_MODAL_HEADER_TEXT = "üÜò Signalez-moi l'erreur"
REPORT_ERROR_LABEL_PLACEHOLDER = "Nom / Pseudo"
REPORT_ERROR_MODAL_NAME_PLACEHOLDER = "Ex : Jane Doe"
REPORT_ERROR_CANCEL_BUTTON_TEXT = "Annuler"
REPORT_ERROR_SUBMIT_BUTTON_TEXT = "Signaler"
REPORT_ERROR_SUCCESS_MESSAGE = "Merci pour votre signalement ! üôè"
REPORT_ERROR_FAILURE_MESSAGE = "Une erreur est survenue lors de l'envoi du signalement. üòû"






# FOR HAVE A RETURN TO THE LINE USE <br> IN MESSAGE

# For 503 errors when maintenance is activated
TEXT_MAINTENANCE_TYPE = "Maintenance serveur"
TEXT_MAINTENANCE_MESSAGE = "Je fais de nouvelles exp√©riences !! <br> Promis je me d√©p√™che ! üòó"
TEXT_MAINTENANCE_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/maintenance.gif"

# For 500 errors when server probably crashed
TEXT_GENERIC_ERROR_TYPE = "Erreur serveur"
TEXT_GENERIC_ERROR_MESSAGE = "Le serveur a s√ªrement d√ª crash... <br> N'h√©sitez pas √† me le signaler !"
TEXT_GENERIC_ERROR_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/generic_error.gif"

# For 504 errors when internet connection is down
TEXT_BOX_ERROR_CODE = [504]
TEXT_BOX_ERROR_TYPE = "Erreur de connexion"
TEXT_BOX_ERROR_MESSAGE = "On dirait que ma box fibre et 4G ont d√©cid√© de faire une pause, <br> il va falloir patienter... üò© N‚Äôh√©sitez pas √† me le signaler quand m√™me !"
TEXT_BOX_ERROR_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/box_error.gif"

 #ONLY FOR ZERO TRUST USER
# For 530 errors when the cloudflare tunnel doesnt work
TEXT_TUNNEL_ERROR_CODE = [530]
TEXT_TUNNEL_ERROR_TYPE = "Erreur Zero Trust"
TEXT_TUNNEL_ERROR_MESSAGE = "On dirait qu'il y a un soucis avec le tunnel cloudflare Zero Trust... <br> N'h√©sitez pas √† me le signaler !"
TEXT_TUNNEL_ERROR_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/box_error.gif"

# For 502 errors when a service is down
TEXT_CONTAINER_ERROR_CODE = [502, 503]
TEXT_CONTAINER_ERROR_TYPE = "Service indisponible"
TEXT_CONTAINER_ERROR_MESSAGE = "Service non d√©marr√© ou plant√© ! <br> N‚Äôh√©sitez pas √† me le signaler au cas o√π !"
TEXT_CONTAINER_ERROR_GIF = "https://raw.githubusercontent.com/JamesDAdams/cloudflare-worker-error-page/refs/heads/main/assets/container_error.gif"

# Enable or disable 4G banner functionality
ENABLE_4G_BANNER = true
# Message for 4G banner when fiber is down
TEXT_4G_BANNER_MESSAGE = "Attention des lenteurs peuvent survenir, ma fibre est H.S. Le serveur fonctionne en 4G !"